#!/bin/sh

echo -e "bruh123469\nbruh123469" | sudo passwd jimmu
echo -e "nachopassword1\nnachopassword1" | sudo passwd suizei
echo -e "makeastrongwarrior14\nmakeastrongwarrior14" | sudo passwd annei
echo -e "wackbro69\nwackbro69" | sudo passwd itoku
echo -e "whateverbruh4\nwhateverbruh4" | sudo passwd kinmei
echo -e "cybercool2\ncybercool2" | sudo passwd bidatsu
echo -e "nonyabiz3\nnonyabiz3" | sudo passwd yomei
echo -e "japaneseculturemyguy\njapaneseculturemyguy" | sudo passwd sushun
echo -e "warriorwayofninja56\nwarriorwayofninja56" | sudo passwd suiko
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd jomei
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd kogyoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd kotoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd saimei
echo -e "samuraiwarriorsforlyfe\nsamuraiwarriorsforlyfe" | sudo passwd tenji
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd kobun
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd jito
echo -e "iamnotokay69\niamnotokay69" | sudo passwd monmu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd gemei
echo -e "59Q6gy48u2\n59Q6gy48u2" | sudo passwd TokugawaIemitsu
echo -e "JHyKN5ZnmG\nJHyKN5ZnmG" | sudo passwd HojoSadatoki
echo -e "GzNbTXRk7F\nGzNbTXRk7F" | sudo passwd AshikagaTakauji
echo -e "7zW9EL2aKB\n7zW9EL2aKB" | sudo passwd MinamotoNoSanetomo
echo -e "rL9madQxjE\nrL9madQxjE" | sudo passwd TokugawaHideyoshi
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd WatanabeKazan
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd EraFusahide
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd NagaoHarukage
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TokiYorinari
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd YamauchiKazutoyo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TaigenSessai
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd WadaShinsuke
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd EnomotoTakeaki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd NaoeKagetsuna
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TakedaShingen
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd YamadaArinobu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd tokugawaiemitsu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd hojosadatoki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd ashikagatakauji
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd minamotonosanetomo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd tokugawahideyoshi
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd watanabekazan
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd erafusahide
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd nagaoharukage
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd tokiyorinari
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd yamauchikazutoyo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd taigensessai
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd wadashinsuke
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd enomototakeaki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd naoekagetsuna
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd takedashingen
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd yamadaarinobu
echo -e "Rb7Z39ejUs\nRb7Z39ejUs" | sudo passwd root

