#!/bin/sh

echo -e "bruh123469\nbruh123469" | sudo passwd jimmu
echo -e "nachopassword1\nnachopassword1" | sudo passwd suizei
echo -e "makeastrongwarrior14\nmakeastrongwarrior14" | sudo passwd annei
echo -e "wackbro69\nwackbro69" | sudo passwd itoku
echo -e "whateverbruh4\nwhateverbruh4" | sudo passwd kinmei
echo -e "cybercool2\ncybercool2" | sudo passwd bidatsu
echo -e "nonyabiz3\nnonyabiz3" | sudo passwd yomei
echo -e "japaneseculturemyguy\njapaneseculturemyguy" | sudo passwd sushun
echo -e "warriorwayofninja56\nwarriorwayofninja56" | sudo passwd suiko
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd jomei
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd kogyoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd kotoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd saimei
echo -e "samuraiwarriorsforlyfe\nsamuraiwarriorsforlyfe" | sudo passwd tenji
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd kobun
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd jito
echo -e "iamnotokay69\niamnotokay69" | sudo passwd monmu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd gemei
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd tokugawaiemitsu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd hojosadatoki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd ashikagatakauji
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd minamotonosanetomo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd tokugawahideyoshi
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd watanabekazan
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd erafusahide
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd nagaoharukage
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd tokiyorinari
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd yamauchikazutoyo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd taigensessai
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd wadashinsuke
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd enomototakeaki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd naoekagetsuna
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd takedashingen
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd yamadaarinobu
