#!/bin/sh

echo -e "bruh123469\nbruh123469" | sudo passwd jimmu
echo -e "nachopassword1\nnachopassword1" | sudo passwd suizei
echo -e "makeastrongwarrior14\nmakeastrongwarrior14" | sudo passwd annei
echo -e "wackbro69\nwackbro69" | sudo passwd itoku
echo -e "whateverbruh4\nwhateverbruh4" | sudo passwd kinmei
echo -e "cybercool2\ncybercool2" | sudo passwd bidatsu
echo -e "nonyabiz3\nnonyabiz3" | sudo passwd yomei
echo -e "japaneseculturemyguy\njapaneseculturemyguy" | sudo passwd sushun
echo -e "warriorwayofninja56\nwarriorwayofninja56" | sudo passwd suiko
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd jomei
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd kogyoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd kotoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd saimei
echo -e "samuraiwarriorsforlyfe\nsamuraiwarriorsforlyfe" | sudo passwd tenji
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd kobun
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd jito
echo -e "iamnotokay69\niamnotokay69" | sudo passwd monmu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd gemei
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TokugawaIemitsu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd HojoSadatoki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd AshikagaTakauji
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd MinamotoNoSanetomo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TokugawaHideyoshi
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd WatanabeKazan
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd EraFusahide
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd NagaoHarukage
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TokiYorinari
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd YamauchiKazutoyo
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TaigenSessai
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd WadaShinsuke
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd EnomotoTakeaki
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd NaoeKagetsuna
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd TakedaShingen
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd YamadaArinobu
