#!/bin/sh

echo -e "bruh123469\nbruh123469" | sudo passwd jimmu
echo -e "nachopassword1\nnachopassword1" | sudo passwd suizei
echo -e "makeastrongwarrior14\nmakeastrongwarrior14" | sudo passwd annei
echo -e "wackbro69\nwackbro69" | sudo passwd itoku
echo -e "whateverbruh4\nwhateverbruh4" | sudo passwd kinmei
echo -e "cybercool2\ncybercool2" | sudo passwd bidatsu
echo -e "nonyabiz3\nnonyabiz3" | sudo passwd yomei
echo -e "japaneseculturemyguy\njapaneseculturemyguy" | sudo passwd sushun
echo -e "warriorwayofninja56\nwarriorwayofninja56" | sudo passwd suiko
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd jomei
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd kogyoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd kotoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd saimei
echo -e "samuraiwarriorsforlyfe\nsamuraiwarriorsforlyfe" | sudo passwd tenji
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd kobun
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd jito
echo -e "iamnotokay69\niamnotokay69" | sudo passwd monmu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd gemei
echo -e "bruh123469\nbruh123469" | sudo passwd Jimmu
echo -e "nachopassword1\nnachopassword1" | sudo passwd Suizei
echo -e "makeastrongwarrior14\nmakeastrongwarrior14" | sudo passwd Annei
echo -e "wackbro69\nwackbro69" | sudo passwd Itoku
echo -e "whateverbruh4\nwhateverbruh4" | sudo passwd Kinmei
echo -e "cybercool2\ncybercool2" | sudo passwd Bidatsu
echo -e "nonyabiz3\nnonyabiz3" | sudo passwd Yomei
echo -e "japaneseculturemyguy\njapaneseculturemyguy" | sudo passwd Sushun
echo -e "warriorwayofninja56\nwarriorwayofninja56" | sudo passwd Suiko
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd Jomei
echo -e "yodonthackme4\nyodonthackme4" | sudo passwd Kogyoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd Kotoku
echo -e "wearenotokay1\nwearenotokay1" | sudo passwd Saimei
echo -e "samuraiwarriorsforlyfe\nsamuraiwarriorsforlyfe" | sudo passwd Tenji
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd Kobun
echo -e "toomanypassnotenoughculture\ntoomanypassnotenoughculture" | sudo passwd Jito
echo -e "iamnotokay69\niamnotokay69" | sudo passwd Monmu
echo -e "plzletuswin6969\nplzletuswin6969" | sudo passwd Gemei
echo -e "59Q6gy48u2\n59Q6gy48u2" | sudo passwd TokugawaIemitsu
echo -e "JHyKN5ZnmG\nJHyKN5ZnmG" | sudo passwd HojoSadatoki
echo -e "GzNbTXRk7F\nGzNbTXRk7F" | sudo passwd AshikagaTakauji
echo -e "7zW9EL2aKB\n7zW9EL2aKB" | sudo passwd MinamotoNoSanetomo
echo -e "rL9madQxjE\nrL9madQxjE" | sudo passwd TokugawaHideyoshi
echo -e "M73JWkRuaA\nM73JWkRuaA" | sudo passwd WatanabeKazan
echo -e "SGcFDHktL9\nSGcFDHktL9" | sudo passwd EraFusahide
echo -e "AJYZmqWT9K\nAJYZmqWT9K" | sudo passwd NagaoHarukage
echo -e "L85AzFJkKv\nL85AzFJkKv" | sudo passwd TokiYorinari
echo -e "AMEg5bsLwQ\nAMEg5bsLwQ" | sudo passwd YamauchiKazutoyo
echo -e "pDrL8KNzHt\npDrL8KNzHt" | sudo passwd TaigenSessai
echo -e "bUr45depn8\nbUr45depn8" | sudo passwd WadaShinsuke
echo -e "94SRZMByjW\n94SRZMByjW" | sudo passwd EnomotoTakeaki
echo -e "KLXFxz3Q5h\nKLXFxz3Q5h" | sudo passwd NaoeKagetsuna
echo -e "c2FUsWYwMu\nc2FUsWYwMu" | sudo passwd TakedaShingen
echo -e "N367LyhqkX\nN367LyhqkX" | sudo passwd YamadaArinobu
echo -e "3ej6Tt54zY\n3ej6Tt54zY" | sudo passwd tokugawaiemitsu
echo -e "wzEFR9YsVu\nwzEFR9YsVu" | sudo passwd hojosadatoki
echo -e "QcrHZnRT97\nQcrHZnRT97" | sudo passwd ashikagatakauji
echo -e "8hXKUdaskZ\n8hXKUdaskZ" | sudo passwd minamotonosanetomo
echo -e "W9yswzhdkN\nW9yswzhdkN" | sudo passwd tokugawahideyoshi
echo -e "TsL38kzRaG\nTsL38kzRaG" | sudo passwd watanabekazan
echo -e "uaUSBZb2hv\nuaUSBZb2hv" | sudo passwd erafusahide
echo -e "ebSHrFgAw2\nebSHrFgAw2" | sudo passwd nagaoharukage
echo -e "Wb598x3v6T\nWb598x3v6T" | sudo passwd tokiyorinari
echo -e "gMWpm3bN8c\ngMWpm3bN8c" | sudo passwd yamauchikazutoyo
echo -e "rqZWPcuKd9\nrqZWPcuKd9" | sudo passwd taigensessai
echo -e "PQwAJ7SELG\nPQwAJ7SELG" | sudo passwd wadashinsuke
echo -e "T3ayzYuLNx\nT3ayzYuLNx" | sudo passwd enomototakeaki
echo -e "bLJSMqA324\nbLJSMqA324" | sudo passwd naoekagetsuna
echo -e "eMRvWzT7kC\neMRvWzT7kC" | sudo passwd takedashingen
echo -e "m4vujUnbct\nm4vujUnbct" | sudo passwd yamadaarinobu
echo -e "8mU6KECvgY\n8mU6KECvgY" | sudo passwd root

